[project]
name = "my-yt-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "cohere>=7.1.0",
    "groq>=1.7.0",
    "numpy>=2.5.2",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
    "torchcodec>=0.16.0",
    "yt-dlp>=2026.8.19",
]
